apiVersion: apps/v1
kind: Deployment
metadata:
 name: lamp-wp
 labels:
   app: http
spec:
 replicas: 1
 selector:
   matchLabels:
     app: http
 template:
  metadata:
   labels:
    app: http
  spec:
   volumes:
   - name: php-config
     configMap:
       name: php-config
   containers:
   - name: http-php-container
     image: webdevops/php-apache:alpine-3-php7
     env:
     - name: MYSQL_ROOT_PASSWORD
       valueFrom:
         secretKeyRef:
           name: mysql-root-password
           key: password
     - name: MYSQL_DATABASE
       valueFrom:
         secretKeyRef:
           name: mysql-db
           key: database
     - name: MYSQL_PASSWORD
       valueFrom:
         secretKeyRef:
           name: mysql-user
           key: password
     - name: MYSQL_USER
       valueFrom:
         secretKeyRef:
           name: mysql-user
           key: user
     - name: MYSQL_HOST
       valueFrom:
         secretKeyRef:
           name: mysql-host
           key: host
     volumeMounts:
     - name: php-config
       mountPath: /opt/docker/etc/php/php.ini
       subPath: php.ini
     ports:
     - containerPort: 80
   - name: mysql-container
     image: mysql:5.6
     env:
     - name: MYSQL_ROOT_PASSWORD
       valueFrom:
         secretKeyRef:
           name: mysql-root-password
           key: password
     - name: MYSQL_DATABASE
       valueFrom:
         secretKeyRef:
           name: mysql-db
           key: database
     - name: MYSQL_PASSWORD
       valueFrom:
         secretKeyRef:
           name: mysql-user
           key: password
     - name: MYSQL_USER
       valueFrom:
         secretKeyRef:
           name: mysql-user
           key: user
     - name: MYSQL_HOST
       valueFrom:
       valueFrom:
         secretKeyRef:
           name: mysql-host
           key: host
     ports:
     - containerPort: 3306