apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-password
type: Opaque
data:
  password: cm9vdA==  # 'password' base64 encoded

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-user
type: Opaque
data:
  user: ZGFu
  password: ZGFuaXNo

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-host
type: Opaque
data:
 host: bXlzcWwtc2VydmljZQ==  ##Use mysql-service as hostname
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-db
type: Opaque
data:
 database: cGhwd2Vi