apiVersion: v1
kind: Pod
metadata:
  name: pod-xfusion
  labels:
    app: nginx
spec:
  containers:
  - name: container-xfusion
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: pv-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: pv-volume # Matches volumeMounts name
    persistentVolumeClaim:
      claimName: pvc-xfusion