apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-xfusion
spec:
  accessModes:
    - ReadWriteOnce # Must match the access modes of a suitable PV
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual