apiVersion: v1
kind: Service
metadata:
  name: iron-db-service-devops
  namespace: iron-namespace-devops
spec:
 selector:
  db: mariadb
 type: ClusterIP
 ports:
 - protocol: TCP
   port: 3306
   targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
 name: iron-gallery-service-devops
 namespace: iron-namespace-devops
spec:
 type: NodePort
 selector:
  run: iron-gallery
 ports:
 - protocol: TCP
   port: 80
   nodePort: 32678