apiVersion: v1
kind: Secret
metadata: 
  name: mysql-root-pass
type: opaque
data:
  password: UjAwdA==

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-user-pass
type: opaque
data:
  username: a29kZWtsb3VkX2pveQ==
  password: a3NIODVVSmpoYg==

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-url
type: opaque
data:
  database: a29kZWtsb3VkX2RiMg==

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-host
type: opaque
data:
  host: bXlzcWwtc2VydmljZQ==