apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-xfusion
spec:
 capacity:
  storage: 4Gi
 storageClassName: manual
 accessModes:
 - ReadWriteOnce
 hostPath:
  path: /mnt/sysops

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: pvc-xfusion
spec:
 storageClassName: manual
 resources:  
  requests:
   storage: 2Gi
 accessModes:
 - ReadWriteOnce
