apiVersion: v1
kind: Secret
metadata:
 name: mysql-root-pass
type: opaque
data:
  password: cm9vdA==
---
apiVersion: v1
kind: Secret
metadata:
 name: mysql-host
type: opaque
data:
 host: ZHJ1cGFsLW15c3FsLXNlcnZpY2U=