apiVersion: v1
kind: Service
metadata:
  name: g-service
spec:
  ports:
    - nodePort: 32000
      port: 3000
      targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: None
  type: NodePort